//! OpenAPI 3 renderer.
//!
//! Generates a single `openapi.json` document: each OSDL model becomes a
//! component schema (`components.schemas.<Model>`), with properties typed per
//! the OpenAPI 3.1 schema dialect. Nullability/required and PK/unique
//! annotations are preserved. Output is deterministic (sorted keys via
//! `serde_json::to_string_pretty`).

#![allow(clippy::result_large_err)]

use osdl_core::Target;
use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::OsdlError;
use osdl_core::types::{FieldType, Intent, ScalarType};
use osdl_core::validator::CodeRenderer;
use serde_json::{Value, json};

/// The OpenAPI renderer.
pub struct OpenApiRenderer {
    target: Target,
}

impl OpenApiRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for OpenApiRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OsdlError> {
        let doc = build_openapi(ast);
        let text = serde_json::to_string_pretty(&doc)
            .map_err(|e| OsdlError::Io(std::io::Error::other(format!("serialize openapi: {e}"))))?;
        Ok(vec![("openapi.json".to_string(), text)])
    }
}

fn oas_scalar(s: ScalarType) -> Value {
    match s {
        ScalarType::String => json!({ "type": "string" }),
        ScalarType::Int => json!({ "type": "integer", "format": "int32" }),
        ScalarType::BigInt => json!({ "type": "integer", "format": "int64" }),
        ScalarType::Float => json!({ "type": "number", "format": "double" }),
        ScalarType::Bool => json!({ "type": "boolean" }),
        ScalarType::DateTime => json!({ "type": "string", "format": "date-time" }),
        ScalarType::Date => json!({ "type": "string", "format": "date" }),
        ScalarType::Uuid => json!({ "type": "string", "format": "uuid" }),
        ScalarType::Json => json!({}),
        ScalarType::Binary => json!({ "type": "string", "format": "binary" }),
    }
}

/// Build the OpenAPI property schema for a field.
fn oas_property(field: &Field) -> Value {
    let mut schema = match &field.ty {
        FieldType::Scalar(s) => oas_scalar(*s),
        FieldType::Ref(r) => json!({ "type": "string", "$comment": format!("FK -> {}", r.model) }),
        FieldType::InferredRef(s) => json!({ "type": "string", "$comment": s }),
    };
    if field.has(Intent::Null) {
        // OpenAPI 3.1: nullable is expressed by a `type` array including "null".
        if let Some(obj) = schema.as_object_mut()
            && let Some(Value::String(t)) = obj.get("type")
        {
            let t = t.clone();
            obj.insert("type".into(), json!([t, "null"]));
        }
    }
    if let Some(expr) = &field.check_expr
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("x-check".into(), json!(expr));
    }
    if field.has(Intent::Virtual)
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("x-virtual".into(), json!(true));
    }
    schema
}

fn build_openapi(ast: &Ast) -> Value {
    let mut schemas = serde_json::Map::new();
    let mut model_names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
    model_names.sort();
    for name in &model_names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        schemas.insert(name.clone(), build_schema(model));
    }
    json!({
        "openapi": "3.1.0",
        "info": {
            "title": "OSDL-generated API",
            "version": "0.1.0",
            "x-source": "Generated by `osdl build --target openapi`. Do not edit by hand.",
        },
        "components": { "schemas": Value::Object(schemas) },
    })
}

fn build_schema(model: &Model) -> Value {
    let mut props = serde_json::Map::new();
    let mut required: Vec<String> = Vec::new();
    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            props.insert(
                format!("{}_type", to_snake(&f.name)),
                json!({ "type": "string", "x-polymorphic": f.polymorphic_targets }),
            );
            props.insert(
                format!("{}_id", to_snake(&f.name)),
                json!({ "type": "string", "format": "uuid" }),
            );
            required.push(format!("{}_type", to_snake(&f.name)));
            required.push(format!("{}_id", to_snake(&f.name)));
            continue;
        }
        props.insert(f.name.clone(), oas_property(f));
        if !f.has(Intent::Null) {
            required.push(f.name.clone());
        }
    }
    let mut schema = serde_json::Map::new();
    schema.insert("type".into(), json!("object"));
    schema.insert("properties".into(), Value::Object(props));
    if !required.is_empty() {
        required.sort();
        schema.insert("required".into(), json!(required));
    }
    Value::Object(schema)
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    fn render(src: &str) -> Value {
        let ast = parse(src).unwrap();
        osdl_core::Validator::validate(&ast, Some(Target::OpenApi)).unwrap();
        let r = OpenApiRenderer::new(Target::OpenApi);
        let files = r.render(&ast).unwrap();
        let (_, text) = &files[0];
        serde_json::from_str(text).unwrap()
    }

    #[test]
    fn emits_component_schemas() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null\n";
        let doc = render(src);
        let schemas = doc["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("User"));
        let user = &schemas["User"];
        let props = user["properties"].as_object().unwrap();
        assert!(props.contains_key("id"));
        assert!(props.contains_key("email"));
        // id is non-null -> required.
        let req = user["required"].as_array().unwrap();
        assert!(req.iter().any(|v| v == "id"));
        // age is nullable -> type array includes "null".
        assert_eq!(props["age"]["type"], json!(["integer", "null"]));
    }

    #[test]
    fn valid_openapi_document() {
        let src = "Post\n  id uuid -pk\n  title string\nVideo\n  id uuid -pk\n";
        let doc = render(src);
        assert_eq!(doc["openapi"], json!("3.1.0"));
        let schemas = doc["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("Post"));
        assert!(schemas.contains_key("Video"));
    }
}
