//! OpenAPI 3 renderer.
//!
//! Generates a single `openapi.json` document: each ODSL model becomes a
//! component schema (`components.schemas.<Model>`), with properties typed per
//! the OpenAPI 3.1 schema dialect. Nullability/required and PK/unique
//! annotations are preserved. Output is deterministic (sorted keys via
//! `serde_json::to_string_pretty`).

#![allow(clippy::result_large_err)]

use odsl_core::Target;
use odsl_core::ast::{Ast, Field, Model};
use odsl_core::errors::OdslError;
use odsl_core::types::{FieldType, Intent, ScalarType};
use odsl_core::validator::CodeRenderer;
use serde_json::{Value, json};

/// The OpenAPI renderer.
pub struct OpenApiRenderer {
    target: Target,
}

impl OpenApiRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for OpenApiRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OdslError> {
        let doc = build_openapi(ast);
        let text = serde_json::to_string_pretty(&doc)
            .map_err(|e| OdslError::Io(std::io::Error::other(format!("serialize openapi: {e}"))))?;
        Ok(vec![("openapi.json".to_string(), text)])
    }
}

fn oas_scalar(s: ScalarType) -> Value {
    match s {
        ScalarType::String => json!({ "type": "string" }),
        ScalarType::Int => json!({ "type": "integer", "format": "int32" }),
        ScalarType::BigInt => json!({ "type": "integer", "format": "int64" }),
        ScalarType::Float => json!({ "type": "number", "format": "double" }),
        ScalarType::Bool => json!({ "type": "boolean" }),
        ScalarType::DateTime => json!({ "type": "string", "format": "date-time" }),
        ScalarType::Date => json!({ "type": "string", "format": "date" }),
        ScalarType::Uuid => json!({ "type": "string", "format": "uuid" }),
        ScalarType::Json => json!({}),
        ScalarType::Binary => json!({ "type": "string", "format": "binary" }),
        ScalarType::Decimal => json!({ "type": "number", "format": "decimal" }),
    }
}

/// Build the OpenAPI property schema for a field.
fn oas_property(field: &Field, model_name: &str, ast: &Ast) -> Value {
    let mut schema = match &field.ty {
        FieldType::Scalar(s) => oas_scalar(*s),
        FieldType::Ref(r) => json!({ "type": "string", "$comment": format!("FK -> {}", r.model) }),
        FieldType::InferredRef(s) => json!({ "type": "string", "$comment": s }),
    };
    if field.has(Intent::Null) {
        // OpenAPI 3.1: nullable is expressed by a `type` array including "null".
        if let Some(obj) = schema.as_object_mut()
            && let Some(Value::String(t)) = obj.get("type")
        {
            let t = t.clone();
            obj.insert("type".into(), json!([t, "null"]));
        }
    }
    if let Some(expr) = &field.check_expr
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("x-check".into(), json!(expr));
    }
    if field.has(Intent::Virtual)
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("x-virtual".into(), json!(true));
    }
    // Doc comment -> `description`; deprecation -> `deprecated: true`.
    if let Some(doc) = ast.field_doc(model_name, &field.name)
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("description".into(), json!(doc));
    }
    if ast.field_deprecation(model_name, &field.name).is_some()
        && let Some(obj) = schema.as_object_mut()
    {
        obj.insert("deprecated".into(), json!(true));
    }
    schema
}

fn build_openapi(ast: &Ast) -> Value {
    let mut schemas = serde_json::Map::new();
    let mut model_names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
    model_names.sort();
    for name in &model_names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        schemas.insert(name.clone(), build_schema(model, ast));
    }
    json!({
        "openapi": "3.1.0",
        "info": {
            "title": "ODSL-generated API",
            "version": "0.1.0",
            "x-source": "Generated by `odsl build --target openapi`. Do not edit by hand.",
        },
        "components": { "schemas": Value::Object(schemas) },
        "paths": build_paths(ast),
    })
}

fn build_paths(ast: &Ast) -> Value {
    let mut paths = serde_json::Map::new();
    let mut model_names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
    model_names.sort();
    for name in &model_names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        let pk = model
            .fields()
            .find(|(_, f)| f.has(Intent::Pk))
            .map(|(_, f)| f)
            .expect("has pk");
        let pk_ty = match &pk.ty {
            FieldType::Scalar(s) => oas_scalar(*s),
            _ => json!({ "type": "string" }),
        };
        let coll = format!("/{}", name.to_lowercase());
        let item = format!("/{}/{{id}}", name.to_lowercase());

        // GET collection + POST create.
        let mut coll_obj = serde_json::Map::new();
        coll_obj.insert(
            "get".to_string(),
            json!({
                "summary": format!("List {}", name),
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": { "type": "array", "items": { "$ref": format!("#/components/schemas/{}", name) } }
                            }
                        }
                    }
                }
            }),
        );
        coll_obj.insert(
            "post".to_string(),
            json!({
                "summary": format!("Create {}", name),
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": { "$ref": format!("#/components/schemas/{}", name) }
                        }
                    }
                },
                "responses": { "201": { "description": "Created" } }
            }),
        );
        paths.insert(coll, Value::Object(coll_obj));

        // GET by id + PUT update + DELETE.
        let mut item_obj = serde_json::Map::new();
        item_obj.insert(
            "get".to_string(),
            json!({
                "summary": format!("Get {} by id", name),
                "parameters": [ { "name": "id", "in": "path", "required": true, "schema": pk_ty } ],
                "responses": { "200": { "description": "OK", "content": { "application/json": { "schema": { "$ref": format!("#/components/schemas/{}", name) } } } } }
            }),
        );
        item_obj.insert(
            "put".to_string(),
            json!({
                "summary": format!("Update {}", name),
                "parameters": [ { "name": "id", "in": "path", "required": true, "schema": pk_ty.clone() } ],
                "requestBody": {
                    "required": true,
                    "content": { "application/json": { "schema": { "$ref": format!("#/components/schemas/{}", name) } } }
                },
                "responses": { "200": { "description": "Updated" } }
            }),
        );
        item_obj.insert(
            "delete".to_string(),
            json!({
                "summary": format!("Delete {}", name),
                "parameters": [ { "name": "id", "in": "path", "required": true, "schema": pk_ty } ],
                "responses": { "204": { "description": "Deleted" } }
            }),
        );
        paths.insert(item, Value::Object(item_obj));
    }
    Value::Object(paths)
}

fn build_schema(model: &Model, ast: &Ast) -> Value {
    let mut props = serde_json::Map::new();
    let mut required: Vec<String> = Vec::new();
    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            props.insert(
                format!("{}_type", to_snake(&f.name)),
                json!({ "type": "string", "x-polymorphic": f.polymorphic_targets }),
            );
            props.insert(
                format!("{}_id", to_snake(&f.name)),
                json!({ "type": "string", "format": "uuid" }),
            );
            required.push(format!("{}_type", to_snake(&f.name)));
            required.push(format!("{}_id", to_snake(&f.name)));
            continue;
        }
        props.insert(f.name.clone(), oas_property(f, &model.name, ast));
        if !f.has(Intent::Null) {
            required.push(f.name.clone());
        }
    }
    let mut schema = serde_json::Map::new();
    schema.insert("type".into(), json!("object"));
    schema.insert("properties".into(), Value::Object(props));
    if !required.is_empty() {
        required.sort();
        schema.insert("required".into(), json!(required));
    }
    // Model-level description.
    if let Some(doc) = ast.model_doc(&model.name) {
        schema.insert("description".into(), json!(doc));
    }
    Value::Object(schema)
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use odsl_parser::parse;

    fn render(src: &str) -> Value {
        let ast = parse(src).unwrap();
        odsl_core::Validator::validate(&ast, Some(Target::OpenApi)).unwrap();
        let r = OpenApiRenderer::new(Target::OpenApi);
        let files = r.render(&ast).unwrap();
        let (_, text) = &files[0];
        serde_json::from_str(text).unwrap()
    }

    #[test]
    fn emits_component_schemas() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null\n";
        let doc = render(src);
        let schemas = doc["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("User"));
        let user = &schemas["User"];
        let props = user["properties"].as_object().unwrap();
        assert!(props.contains_key("id"));
        assert!(props.contains_key("email"));
        // id is non-null -> required.
        let req = user["required"].as_array().unwrap();
        assert!(req.iter().any(|v| v == "id"));
        // age is nullable -> type array includes "null".
        assert_eq!(props["age"]["type"], json!(["integer", "null"]));
    }

    #[test]
    fn valid_openapi_document() {
        let src = "Post\n  id uuid -pk\n  title string\nVideo\n  id uuid -pk\n";
        let doc = render(src);
        assert_eq!(doc["openapi"], json!("3.1.0"));
        let schemas = doc["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("Post"));
        assert!(schemas.contains_key("Video"));
    }

    #[test]
    fn emits_paths_with_crud() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n";
        let doc = render(src);
        let paths = doc["paths"].as_object().unwrap();
        assert!(paths.contains_key("/user"), "got: {paths:?}");
        assert!(paths.contains_key("/user/{id}"));
        // CRUD operations present.
        assert!(paths["/user"].get("get").is_some());
        assert!(paths["/user"].get("post").is_some());
        assert!(paths["/user/{id}"].get("get").is_some());
        assert!(paths["/user/{id}"].get("put").is_some());
        assert!(paths["/user/{id}"].get("delete").is_some());
        // The item path parameter references the PK type.
        let get_params = paths["/user/{id}"]["get"]["parameters"].as_array().unwrap();
        assert_eq!(get_params[0]["name"], json!("id"));
    }

    #[test]
    fn emits_description_and_deprecation() {
        let src = "/// A registered account holder.
User
  id uuid -pk
  /// The user's primary email address.
  email string -uniq -deprecated \"use contactEmail instead\"
";
        let doc = render(src);
        let user = &doc["components"]["schemas"]["User"];
        assert_eq!(user["description"], json!("A registered account holder."));
        let email = &user["properties"]["email"];
        assert_eq!(
            email["description"],
            json!("The user's primary email address.")
        );
        assert_eq!(email["deprecated"], json!(true));
    }
}
