//! GraphQL (SDL) renderer.
//!
//! Generates one `.graphql` document containing a `type` per OSDL model, with
//! scalars mapped to GraphQL built-in types, references as `ID` (or object
//! type references), nullability/optionality preserved, and PK/uniqueness
//! surfaced as directives. Output is deterministic and model-sorted.

#![allow(clippy::result_large_err)]

use osdl_core::Target;
use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::OsdlError;
use osdl_core::types::{FieldType, Intent, ScalarType};
use osdl_core::validator::CodeRenderer;

/// The GraphQL renderer.
pub struct GraphQLRenderer {
    target: Target,
}

impl GraphQLRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for GraphQLRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OsdlError> {
        let mut names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
        names.sort();
        let mut types = Vec::new();
        for name in &names {
            let (_, model) = ast
                .models()
                .find(|(_, m)| &m.name == name)
                .expect("model exists");
            types.push(render_type(model));
        }
        let schema = format!(
            "# Generated by `osdl build --target graphql`. Do not edit by hand.\n\
             # Source of truth: the OSDL schema.\n\n{}\n",
            types.join("\n\n")
        );
        Ok(vec![("schema.graphql".to_string(), schema)])
    }
}

fn gql_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::BigInt => "Int",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Boolean",
        ScalarType::DateTime => "String",
        ScalarType::Date => "String",
        ScalarType::Uuid => "ID",
        ScalarType::Json => "JSON",
        ScalarType::Binary => "String",
    }
}

/// Map a field to its GraphQL type (non-null suffix `!` is added by the caller
/// based on the `-null`/`-pk` intent).
fn gql_base_type(field: &Field) -> String {
    match &field.ty {
        FieldType::Scalar(s) => gql_scalar(*s).to_string(),
        FieldType::Ref(r) => r.model.clone(),
        FieldType::InferredRef(s) => s.clone(),
    }
}

fn render_type(model: &Model) -> String {
    let mut lines = Vec::new();
    lines.push(format!("type {name} {{", name = model.name));

    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            lines.push(format!("  {}: String!", to_snake(&f.name) + "_type"));
            lines.push(format!("  {}: ID!", to_snake(&f.name) + "_id"));
            lines.push(format!(
                "  # polymorphic ref -> {}",
                f.polymorphic_targets.join(", ")
            ));
            continue;
        }
        // GraphQL: a non-null field is `T!`; nullable is `T`.
        let required = !f.has(Intent::Null);
        let base = gql_base_type(f);
        let ty = if required { format!("{base}!") } else { base };
        let mut directives = Vec::new();
        if f.has(Intent::Pk) {
            directives.push("@id".to_string());
        }
        if f.has(Intent::Uniq) {
            directives.push("@unique".to_string());
        }
        if f.has(Intent::Virtual) {
            directives.push("@virtual".to_string());
        }
        if let Some(expr) = &f.check_expr {
            directives.push(format!("@constraint(expression: \"{expr}\")"));
        }
        lines.push(format!(
            "  {name}: {ty}{dirs}",
            name = f.name,
            ty = ty,
            dirs = if directives.is_empty() {
                String::new()
            } else {
                format!(" {}", directives.join(" "))
            }
        ));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    fn render(src: &str) -> String {
        let ast = parse(src).unwrap();
        osdl_core::Validator::validate(&ast, Some(Target::GraphQl)).unwrap();
        let r = GraphQLRenderer::new(Target::GraphQl);
        let files = r.render(&ast).unwrap();
        files.into_iter().map(|(_, c)| c).collect::<String>()
    }

    #[test]
    fn emits_type_with_nonnull() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null\n";
        let out = render(src);
        assert!(out.contains("type User {"));
        assert!(out.contains("id: ID! @id"));
        assert!(out.contains("email: String! @unique"));
        assert!(out.contains("age: Int"));
    }

    #[test]
    fn reference_is_object_type() {
        let src = "Post\n  id uuid -pk\n  author User.id\nUser\n  id uuid -pk\n";
        let out = render(src);
        assert!(
            out.contains("author: User!") || out.contains("author: User"),
            "got: {out}"
        );
    }
}
