[package]
name = "osdl-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
osdl-core = { workspace = true }
osdl-parser = { workspace = true }
osdl-codegen-seaorm = { workspace = true }
osdl-codegen-mongo = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "pipeline"
harness = false
