//! GraphQL (SDL) renderer.
//!
//! Generates one `.graphql` document containing a `type` per ODSL model, with
//! scalars mapped to GraphQL built-in types, references as `ID` (or object
//! type references), nullability/optionality preserved, and PK/uniqueness
//! surfaced as directives. Output is deterministic and model-sorted.

#![allow(clippy::result_large_err)]

use odsl_core::Target;
use odsl_core::ast::{Ast, Field, Model};
use odsl_core::errors::OdslError;
use odsl_core::types::{FieldType, Intent, ScalarType};
use odsl_core::validator::CodeRenderer;

/// The GraphQL renderer.
pub struct GraphQLRenderer {
    target: Target,
}

impl GraphQLRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for GraphQLRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OdslError> {
        let mut names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
        names.sort();
        let mut types = Vec::new();
        for name in &names {
            let (_, model) = ast
                .models()
                .find(|(_, m)| &m.name == name)
                .expect("model exists");
            types.push(render_type(model, ast));
        }
        let schema = format!(
            "# Generated by `odsl build --target graphql`. Do not edit by hand.\n\
             # Source of truth: the ODSL schema.\n\n{}\n\n{}\n",
            types.join("\n\n"),
            render_roots(&names, ast)
        );
        Ok(vec![("schema.graphql".to_string(), schema)])
    }
}

fn gql_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::BigInt => "Int",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Boolean",
        ScalarType::DateTime => "String",
        ScalarType::Date => "String",
        ScalarType::Uuid => "ID",
        ScalarType::Json => "JSON",
        ScalarType::Binary => "String",
        ScalarType::Decimal => "Float", // GraphQL has no decimal; Float is the closest representation
    }
}

/// Map a field to its GraphQL type (non-null suffix `!` is added by the caller
/// based on the `-null`/`-pk` intent).
fn gql_base_type(field: &Field) -> String {
    match &field.ty {
        FieldType::Scalar(s) => gql_scalar(*s).to_string(),
        FieldType::Ref(r) => r.model.clone(),
        FieldType::InferredRef(s) => s.clone(),
    }
}

fn render_roots(names: &[String], ast: &Ast) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push("# CRUD operations (generated).".to_string());

    // One input type per model (all fields optional -> create/update payload).
    for name in names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
        fields.sort_by(|a, b| a.name.cmp(&b.name));
        let mut in_lines = Vec::new();
        in_lines.push(format!("input {name}Input {{"));
        for f in &fields {
            if !f.polymorphic_targets.is_empty() {
                in_lines.push(format!("  {}: String", to_snake(&f.name) + "_type"));
                in_lines.push(format!("  {}: ID", to_snake(&f.name) + "_id"));
                continue;
            }
            let required = !f.has(Intent::Null);
            let base = gql_base_type(f);
            let ty = if required { format!("{base}!") } else { base };
            in_lines.push(format!("  {}: {ty}", f.name));
        }
        in_lines.push("}".to_string());
        lines.push(in_lines.join("\n"));
    }

    // Query: list + get-by-id per model.
    let mut query = Vec::new();
    query.push("type Query {".to_string());
    for name in names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        let pk = model
            .pk_columns()
            .first()
            .and_then(|name| {
                model
                    .fields()
                    .find(|(_, f)| &f.name == name)
                    .map(|(_, f)| f)
            })
            .expect("has pk");
        let pk_ty = gql_base_type(pk);
        let lname = name.to_lowercase();
        query.push(format!("  {}s: [{}!]!", lname, name));
        query.push(format!("  {}(id: {pk_ty}!): {}", lname, name));
    }
    query.push("}".to_string());
    lines.push(query.join("\n"));

    // Mutation: create / update / delete per model.
    let mut mutation = Vec::new();
    mutation.push("type Mutation {".to_string());
    for name in names {
        mutation.push(format!("  create{}(input: {name}Input!): {}!", name, name));
        mutation.push(format!(
            "  update{}(id: ID!, input: {name}Input!): {}",
            name, name
        ));
        mutation.push(format!("  delete{}(id: ID!): Boolean!", name));
    }
    mutation.push("}".to_string());
    lines.push(mutation.join("\n"));

    lines.join("\n\n")
}

fn render_type(model: &Model, ast: &Ast) -> String {
    let mut lines = Vec::new();
    // Model-level description (GraphQL `"""doc"""`).
    if let Some(doc) = ast.model_doc(&model.name) {
        lines.push("\"\"\"".to_string());
        for line in doc.lines() {
            lines.push(line.to_string());
        }
        lines.push("\"\"\"".to_string());
    }
    lines.push(format!("type {name} {{", name = model.name));

    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            lines.push(format!("  {}: String!", to_snake(&f.name) + "_type"));
            lines.push(format!("  {}: ID!", to_snake(&f.name) + "_id"));
            lines.push(format!(
                "  # polymorphic ref -> {}",
                f.polymorphic_targets.join(", ")
            ));
            continue;
        }
        // Field-level description (GraphQL `"""doc"""`).
        if let Some(doc) = ast.field_doc(&model.name, &f.name) {
            lines.push("  \"\"\"".to_string());
            for line in doc.lines() {
                lines.push(format!("  {line}"));
            }
            lines.push("  \"\"\"".to_string());
        }
        // GraphQL: a non-null field is `T!`; nullable is `T`.
        let required = !f.has(Intent::Null);
        let base = gql_base_type(f);
        let ty = if required { format!("{base}!") } else { base };
        let mut directives = Vec::new();
        if f.has(Intent::Pk) {
            directives.push("@id".to_string());
        }
        if f.has(Intent::Uniq) {
            directives.push("@unique".to_string());
        }
        if f.has(Intent::Virtual) {
            directives.push("@virtual".to_string());
        }
        if let Some(expr) = &f.check_expr {
            directives.push(format!("@constraint(expression: \"{expr}\")"));
        }
        if let Some(reason) = ast.field_deprecation(&model.name, &f.name) {
            directives.push(format!("@deprecated(reason: \"{reason}\")"));
        }
        lines.push(format!(
            "  {name}: {ty}{dirs}",
            name = f.name,
            ty = ty,
            dirs = if directives.is_empty() {
                String::new()
            } else {
                format!(" {}", directives.join(" "))
            }
        ));
    }

    lines.push("}".to_string());
    lines.join("\n")
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use odsl_parser::parse;

    fn render(src: &str) -> String {
        let ast = parse(src).unwrap();
        odsl_core::Validator::validate(&ast, Some(Target::GraphQl)).unwrap();
        let r = GraphQLRenderer::new(Target::GraphQl);
        let files = r.render(&ast).unwrap();
        files.into_iter().map(|(_, c)| c).collect::<String>()
    }

    #[test]
    fn emits_type_with_nonnull() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null\n";
        let out = render(src);
        assert!(out.contains("type User {"));
        assert!(out.contains("id: ID! @id"));
        assert!(out.contains("email: String! @unique"));
        assert!(out.contains("age: Int"));
    }

    #[test]
    fn reference_is_object_type() {
        let src = "Post\n  id uuid -pk\n  author User.id\nUser\n  id uuid -pk\n";
        let out = render(src);
        assert!(
            out.contains("author: User!") || out.contains("author: User"),
            "got: {out}"
        );
    }

    #[test]
    fn emits_query_and_mutation_roots() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n";
        let out = render(src);
        assert!(out.contains("type Query {"));
        assert!(out.contains("users: [User!]!"));
        assert!(out.contains("user(id: ID!): User"));
        assert!(out.contains("type Mutation {"));
        assert!(out.contains("createUser(input: UserInput!): User!"));
        assert!(out.contains("deleteUser(id: ID!): Boolean!"));
        // Input type emitted for create/update payloads.
        assert!(out.contains("input UserInput {"));
    }

    #[test]
    fn renders_description_and_deprecation() {
        let src = "/// A registered account holder.
User
  id uuid -pk
  /// The user's primary email address.
  email string -uniq -deprecated \"use contactEmail instead\"
";
        let out = render(src);
        assert!(out.contains("\"\"\"\nA registered account holder.\n\"\"\""));
        assert!(out.contains("  \"\"\"\n  The user's primary email address.\n  \"\"\""));
        assert!(out.contains("@deprecated(reason: \"use contactEmail instead\")"));
    }
}
