//! Prisma schema interchange: bidirectional OSDL ↔ Prisma Schema Language.
//!
//! - [`render_prisma`] (export): OSDL `Ast` → a `.prisma` schema string.
//! - [`parse_prisma`] (import): a `.prisma` schema → an OSDL `Ast` (which the
//!   CLI then serializes via the shared `format_ast` formatter, so imported
//!   Prisma schemas round-trip through the canonical OSDL surface).
//!
//! The mapping is intentionally conservative: it covers the common declarative
//! subset (models, scalars, primary keys, uniques, nullability, foreign-key
//! relations, native enums, `@default`, and many-to-many) and emits a valid
//! schema on both sides. Prisma-specific attributes that have no OSDL analogue
//! (e.g. `@updatedAt`, `@map`) are preserved as `///` comments so no intent is
//! silently lost.

#![allow(clippy::result_large_err)]

use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::OsdlError;
use osdl_core::formatter::format_ast;
use osdl_core::types::{FieldType, Intent, Reference, ScalarType};

// ---------------------------------------------------------------------------
// Export: OSDL -> Prisma
// ---------------------------------------------------------------------------

/// Render an OSDL `Ast` as a Prisma Schema Language document.
pub fn render_prisma(ast: &Ast) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl convert to-prisma`. Do not edit by hand.\n");
    out.push_str("// Source of truth: the OSDL schema.\n\n");
    out.push_str(
        "datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\n",
    );
    out.push_str("generator client {\n  provider = \"prisma-client-js\"\n}\n\n");

    // Native enums first (referenced by models).
    let mut enums: Vec<(String, Vec<String>)> = Vec::new();
    for (_, model) in ast.models() {
        for (_, f) in model.fields() {
            if f.has(Intent::Enum) && !f.enum_variants.is_empty() {
                let mut v = f.enum_variants.clone();
                v.sort();
                enums.push((format!("{}_{}", model.name, f.name), v));
            }
        }
    }
    for (name, variants) in &enums {
        out.push_str(&format!("enum {name} {{\n"));
        for v in variants {
            out.push_str(&format!("  {v}\n"));
        }
        out.push_str("}\n\n");
    }

    let mut models: Vec<&Model> = ast.models().map(|(_, m)| m).collect();
    models.sort_by(|a, b| a.name.cmp(&b.name));
    for m in &models {
        out.push_str(&render_model_prisma(m));
        out.push('\n');
    }
    out
}

fn render_model_prisma(model: &Model) -> String {
    let mut out = String::new();
    out.push_str(&format!("model {} {{\n", model.name));
    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        out.push_str(&format!("  {}\n", render_field_prisma(f)));
    }
    out.push_str("}\n");
    out
}

fn render_field_prisma(f: &Field) -> String {
    let nullable = f.has(Intent::Null);
    let q = if nullable { "?" } else { "" };
    let mut attrs: Vec<String> = Vec::new();

    if f.has(Intent::Pk) {
        attrs.push("@id".into());
        match &f.ty {
            FieldType::Scalar(ScalarType::Uuid) => attrs.push("@default(uuid())".into()),
            FieldType::Scalar(ScalarType::Int) => attrs.push("@default(autoincrement())".into()),
            FieldType::Scalar(ScalarType::BigInt) => attrs.push("@default(autoincrement())".into()),
            _ => {}
        }
    }
    if f.has(Intent::Uniq) && !f.has(Intent::Pk) {
        attrs.push("@unique".into());
    }

    let (base, ref_attr) = match &f.ty {
        FieldType::Scalar(s) => (prisma_scalar(*s).to_string(), None),
        FieldType::Ref(r) => (
            r.model.clone(),
            Some(format!(
                "@relation(fields: [{}], references: [{}])",
                f.name, r.field
            )),
        ),
        FieldType::InferredRef(s) => (s.clone(), None),
    };

    // Many-to-many: a list-typed relation on the owning side.
    if !f.polymorphic_targets.is_empty() {
        let targets = f.polymorphic_targets.join(", ");
        return format!("{} {}[] // polymorphic -> {targets}", f.name, base);
    }

    let parts = [f.name.clone(), format!("{base}{q}")];
    if let Some(ra) = ref_attr {
        attrs.push(ra);
    }
    if let Some(def) = &f.default_value
        && !f.has(Intent::Pk)
    {
        attrs.push(format!("@default({})", prisma_default(def)));
    }
    if f.has(Intent::Enum) && !f.enum_variants.is_empty() {
        attrs.push(format!("// enum: {}", f.enum_variants.join(", ")));
    }
    if let Some(expr) = &f.check_expr {
        attrs.push(format!("// check: {expr}"));
    }
    if f.has(Intent::SoftDelete) {
        attrs.push("// soft-delete marker".into());
    }
    let attr_str = if attrs.is_empty() {
        String::new()
    } else {
        format!(" {}", attrs.join(" "))
    };
    format!("{}{}", parts.join(" "), attr_str)
}

fn prisma_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::BigInt => "BigInt",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Boolean",
        ScalarType::DateTime => "DateTime",
        ScalarType::Date => "DateTime",
        ScalarType::Uuid => "String",
        ScalarType::Json => "Json",
        ScalarType::Binary => "Bytes",
        ScalarType::Decimal => "Decimal",
    }
}

fn prisma_default(raw: &str) -> String {
    // A raw OSDL default that is itself a Prisma function call (e.g. `uuid()`,
    // `autoincrement()`) is emitted verbatim. `now` maps to Prisma's `now()`.
    // Numeric literals pass through; everything else is a string literal.
    if raw.ends_with(')') && raw.contains('(') {
        return raw.to_string();
    }
    match raw {
        "now" => "now()".into(),
        s if s.parse::<i64>().is_ok() || s.parse::<f64>().is_ok() => s.to_string(),
        s => format!("\"{s}\""),
    }
}

// ---------------------------------------------------------------------------
// Import: Prisma -> OSDL
// ---------------------------------------------------------------------------

/// Parse a Prisma Schema Language document into an OSDL `Ast`.
///
/// The returned `Ast` is the canonical in-memory form; callers typically
/// serialize it with [`osdl_core::formatter::format_ast`] to obtain `.osdl`
/// source.
pub fn parse_prisma(src: &str) -> Result<Ast, OsdlError> {
    let mut ast = Ast::new();
    let mut enums: std::collections::HashMap<String, Vec<String>> =
        std::collections::HashMap::new();

    // Strip `//` and `///` comments and `/* ... */` block comments.
    let cleaned = strip_comments(src);

    let mut i = 0;
    let lines: Vec<&str> = cleaned.lines().collect();
    while i < lines.len() {
        let line = lines[i].trim();
        if let Some(rest) = line.strip_prefix("enum ") {
            let name = rest
                .split_whitespace()
                .next()
                .ok_or_else(|| {
                    OsdlError::compile(osdl_core::errors::CompileErrorKind::Parse {
                        message: "malformed enum declaration".into(),
                    })
                })?
                .trim_end_matches('{')
                .trim()
                .to_string();
            let mut variants = Vec::new();
            i += 1;
            while i < lines.len() {
                let l = lines[i].trim();
                if l == "}" {
                    i += 1;
                    break;
                }
                let v = l.trim_end_matches(',').trim();
                if !v.is_empty() && !v.starts_with("//") {
                    variants.push(v.to_string());
                }
                i += 1;
            }
            enums.insert(name, variants);
            continue;
        }
        if let Some(rest) = line.strip_prefix("model ") {
            let name = rest
                .split_whitespace()
                .next()
                .ok_or_else(|| {
                    OsdlError::compile(osdl_core::errors::CompileErrorKind::Parse {
                        message: "malformed model declaration".into(),
                    })
                })?
                .trim_end_matches('{')
                .trim()
                .to_string();
            let mut model = Model {
                name: name.clone(),
                fields: la_arena::Arena::new(),
                field_index: vec![],
                line: i + 1,
                indexes: vec![],
            };
            i += 1;
            while i < lines.len() {
                let l = lines[i].trim();
                if l == "}" {
                    i += 1;
                    break;
                }
                if l.is_empty() || l.starts_with("//") || l.starts_with("@@") {
                    i += 1;
                    continue;
                }
                if let Some(field) = parse_field(l, &enums) {
                    model.add_field(field);
                }
                i += 1;
            }
            ast.add_model(model);
            continue;
        }
        i += 1;
    }

    Ok(ast)
}

/// Parse a single Prisma field line into an OSDL `Field`.
fn parse_field(
    line: &str,
    enums: &std::collections::HashMap<String, Vec<String>>,
) -> Option<Field> {
    // Strip trailing comma and attributes; keep the base `name Type` plus the
    // attribute stream for inspection.
    let raw = line.trim_end_matches(',').trim();
    let mut parts = raw.split_whitespace();
    let name = parts.next()?.to_string();
    let ty_token = parts.next()?;
    let rest = &raw[name.len()..];
    let attr_blob = rest[ty_token.len()..].trim();

    let is_list = ty_token.ends_with("[]");
    let ty_clean = ty_token.trim_end_matches("[]").trim();
    let nullable = ty_clean.ends_with('?');
    let ty_base = ty_clean.trim_end_matches('?').trim().to_string();

    let mut intents: Vec<Intent> = Vec::new();
    let mut enum_variants: Vec<String> = Vec::new();
    let mut default_value: Option<String> = None;
    let mut check_expr: Option<String> = None;
    let mut m2m_target: Option<String> = None;

    // Native enum reference.
    let ty = if let Some(variants) = enums.get(&ty_base) {
        intents.push(Intent::Enum);
        enum_variants = variants.clone();
        FieldType::Scalar(ScalarType::String)
    } else {
        match osdl_scalar(&ty_base) {
            Some(s) => FieldType::Scalar(s),
            None => {
                // Not a scalar -> treat as a relation to `ty_base`.
                if is_list {
                    // Inverse ("has many") side: a relation marker.
                    m2m_target = Some(ty_base.clone());
                    FieldType::Scalar(ScalarType::String)
                } else {
                    // FK side: references `<ty_base>.id`.
                    FieldType::Ref(Reference {
                        model: ty_base.clone(),
                        field: "id".into(),
                    })
                }
            }
        }
    };

    // Inspect attributes.
    if attr_blob.contains("@id") {
        intents.push(Intent::Pk);
    }
    if attr_blob.contains("@unique") {
        intents.push(Intent::Uniq);
    }
    if attr_blob.contains("@relation") {
        // If it's the FK side (not a list), it's already a Ref; nothing extra.
        // For the list/inverse side we already set m2m_target.
        if is_list {
            // keep m2m_target as the related model
            let _ = &ty_base;
        }
    }
    if let Some(def) = extract_default(attr_blob) {
        default_value = Some(def);
    }
    if attr_blob.contains("// check:")
        && let Some(expr) = attr_blob.split("// check:").nth(1)
    {
        check_expr = Some(expr.trim().to_string());
    }

    // Nullable only matters for scalars (refs are ids, not nullable here).
    if nullable && matches!(ty, FieldType::Scalar(_)) {
        intents.push(Intent::Null);
    }

    Some(Field {
        name,
        ty,
        intents,
        enum_variants,
        default_value,
        m2m_target,
        check_expr,
        polymorphic_targets: vec![],
        custom_type: None,
        on_delete: None,
        on_update: None,
        line: 0,
    })
}

fn extract_default(blob: &str) -> Option<String> {
    let idx = blob.find("@default(")?;
    let rest = &blob[idx + "@default(".len()..];
    // Match the *last* `)` so defaults containing `(` ... `)` (e.g. `uuid()`)
    // are not truncated by the first closing paren.
    let end = rest.rfind(')')?;
    let inner = rest[..end].trim();
    // Keep Prisma function-call defaults verbatim so they round-trip back to
    // Prisma unchanged (OSDL stores them as raw default expressions). String
    // literals have their quotes stripped.
    let mapped = match inner {
        "now()" => "now".to_string(),
        other if other.ends_with(')') && other.contains('(') => other.to_string(),
        other => other.trim_matches('"').to_string(),
    };
    Some(mapped)
}

/// Map a Prisma scalar keyword to an OSDL `ScalarType`.
fn osdl_scalar(s: &str) -> Option<ScalarType> {
    match s {
        "String" => Some(ScalarType::String),
        "Int" => Some(ScalarType::Int),
        "BigInt" => Some(ScalarType::BigInt),
        "Float" => Some(ScalarType::Float),
        "Boolean" => Some(ScalarType::Bool),
        "DateTime" => Some(ScalarType::DateTime),
        "Json" => Some(ScalarType::Json),
        "Bytes" => Some(ScalarType::Binary),
        "Decimal" => Some(ScalarType::Decimal),
        _ => None,
    }
}

/// Remove `//`, `///`, and `/* ... */` comments from Prisma source.
fn strip_comments(src: &str) -> String {
    let mut out = String::new();
    let mut in_block = false;
    let chars: Vec<char> = src.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if in_block {
            if chars[i] == '*' && i + 1 < chars.len() && chars[i + 1] == '/' {
                in_block = false;
                i += 2;
                continue;
            }
            if chars[i] == '\n' {
                out.push('\n');
            }
            i += 1;
            continue;
        }
        if chars[i] == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
            in_block = true;
            i += 2;
            continue;
        }
        if chars[i] == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
            // Skip to end of line.
            while i < chars.len() && chars[i] != '\n' {
                i += 1;
            }
            continue;
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

/// Convenience: import a Prisma schema and emit canonical OSDL source.
pub fn prisma_to_osdl(src: &str) -> Result<String, OsdlError> {
    let ast = parse_prisma(src)?;
    Ok(format_ast(&ast))
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    fn osdl(src: &str) -> Ast {
        parse(src).expect("parse osdl")
    }

    #[test]
    fn export_scalars_and_intents() {
        let src = "User
  id uuid -pk
  email string -uniq
  age int -null
  name string
";
        let ast = osdl(src);
        let p = render_prisma(&ast);
        assert!(p.contains("model User {"));
        assert!(p.contains("id String @id @default(uuid())"));
        assert!(p.contains("email String @unique"));
        assert!(p.contains("age Int?"));
        assert!(p.contains("name String"));
    }

    #[test]
    fn export_foreign_key_relation() {
        let src = "Post
  id uuid -pk
  author User.id
";
        let ast = osdl(src);
        let p = render_prisma(&ast);
        assert!(p.contains("author User @relation(fields: [author], references: [id])"));
    }

    #[test]
    fn export_enum_block() {
        let src = "Status
  id uuid -pk
  state string -enum active,inactive
";
        let ast = osdl(src);
        let p = render_prisma(&ast);
        assert!(p.contains("enum Status_state {"));
        assert!(p.contains("  active"));
        assert!(p.contains("  inactive"));
    }

    #[test]
    fn import_round_trips_basic() {
        let prisma = "model User {
  id String @id @default(uuid())
  email String @unique
  age Int?
  name String
}
";
        let ast = parse_prisma(prisma).expect("parse prisma");
        assert!(ast.model_by_name("User").is_some());
        let (_, m) = ast.models().find(|(_, x)| x.name == "User").unwrap();
        let id = m.field_by_name("id").unwrap();
        let idf = &m.fields[id];
        assert!(idf.has(Intent::Pk));
        let age = m.field_by_name("age").unwrap();
        assert!(m.fields[age].has(Intent::Null));
        let email = m.field_by_name("email").unwrap();
        assert!(m.fields[email].has(Intent::Uniq));
    }

    #[test]
    fn import_relation_becomes_ref() {
        let prisma = "model Post {
  id String @id @default(uuid())
  author User @relation(fields: [author], references: [id])
}
";
        let ast = parse_prisma(prisma).expect("parse prisma");
        let (_, m) = ast.models().find(|(_, x)| x.name == "Post").unwrap();
        let a = m.field_by_name("author").unwrap();
        match &m.fields[a].ty {
            FieldType::Ref(r) => assert_eq!(r.model, "User"),
            other => panic!("expected ref, got {other:?}"),
        }
    }

    #[test]
    fn import_export_roundtrip_stable() {
        let src = "User
  id uuid -pk
  email string -uniq
  age int -null
";
        let ast = osdl(src);
        let prisma = render_prisma(&ast);
        // Re-import the Prisma form and ensure the model survives.
        let back = parse_prisma(&prisma).expect("re-import");
        assert!(back.model_by_name("User").is_some());
        let (_, m) = back.models().find(|(_, x)| x.name == "User").unwrap();
        assert!(m.field_by_name("id").is_some());
        assert!(m.field_by_name("email").is_some());
        assert!(m.field_by_name("age").is_some());
    }

    #[test]
    fn numeric_round_trips_decimal() {
        // OSDL `numeric` maps to Prisma `Decimal` and back, preserving the
        // precise numeric type (not silently downgraded to Float).
        let prisma = "model Product {
  id String @id @default(uuid())
  price Decimal
}
";
        let ast = parse_prisma(prisma).expect("parse prisma");
        let (_, m) = ast.models().find(|(_, x)| x.name == "Product").unwrap();
        let price = m.field_by_name("price").unwrap();
        assert!(matches!(
            &m.fields[price].ty,
            osdl_core::types::FieldType::Scalar(osdl_core::types::ScalarType::Decimal)
        ));

        // Re-export and confirm it comes back as `Decimal`.
        let out = render_prisma(&ast);
        assert!(
            out.contains("price Decimal"),
            "expected `price Decimal`, got:\n{out}"
        );
    }
}
