[package]
name = "odsl-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
odsl-core = { workspace = true }
odsl-parser = { workspace = true }
odsl-codegen-seaorm = { workspace = true }
odsl-codegen-mongo = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "pipeline"
harness = false
