//! tRPC router generator.
//!
//! Builds, from one OSDL schema, a set of tRPC v10 routers — one per model —
//! each exposing CRUD procedures (`list`, `get`, `create`, `update`, `remove`)
//! with Zod-validated input/output schemas. tRPC routers are Zod-native, so
//! this crate reuses the Zod field expressions from `osdl-codegen-ts-validators`
//! (single source of truth for the validation vocabulary) and layers the router
//! scaffolding on top.
//!
//! Output:
//!   - `<Model>.router.ts` — the router + its input schemas.
//!   - `routers.ts` — a barrel that merges every router into the app router.
//!   - `index.ts` — re-exports `appRouter`.

#![allow(clippy::result_large_err)]

use osdl_codegen_ts_validators::zod_field_schema;
use osdl_core::Target;
use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::OsdlError;
use osdl_core::types::Intent;
use osdl_core::validator::CodeRenderer;

/// The tRPC renderer.
pub struct TrpcRenderer {
    target: Target,
}

impl TrpcRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for TrpcRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OsdlError> {
        let mut files = Vec::new();
        let mut names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
        names.sort();
        let mut routers: Vec<String> = Vec::new();
        for name in &names {
            let (_, model) = ast
                .models()
                .find(|(_, m)| &m.name == name)
                .expect("model exists");
            let router_name = format!("{name}Router");
            routers.push(router_name);
            files.push((format!("{name}.router.ts"), render_router(model, ast)));
        }
        files.push(("routers.ts".to_string(), render_barrel(&routers)));
        files.push(("index.ts".to_string(), render_index(&routers)));
        Ok(files)
    }
}

/// Fields that are auto-managed (PK, soft-delete marker) and so are excluded
/// from a client-supplied `create`/`update` input. (Auto timestamps such as
/// `createdAt`/`updatedAt` are conventionally `-auto`/`-default now` columns;
/// they remain client-editable here since OSDL has no dedicated audit intent.)
fn is_managed(field: &Field) -> bool {
    field.has(Intent::Pk) || field.has(Intent::SoftDelete)
}

/// Build the field entries for a Zod object schema (the body of
/// `z.object({ ... })`).
fn zod_object_body(model: &Model, ast: &Ast, include_managed: bool) -> Vec<String> {
    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    let mut entries = Vec::new();
    for f in &fields {
        if !include_managed && is_managed(f) {
            continue;
        }
        if !f.polymorphic_targets.is_empty() {
            let t = format!("{}_type", to_snake(&f.name));
            let i = format!("{}_id", to_snake(&f.name));
            entries.push(format!("  {t}: z.string(),"));
            entries.push(format!("  {i}: z.string(),"));
            continue;
        }
        entries.push(format!("  {}: {},", f.name, zod_field_schema(f)));
    }
    // Avoid an empty object literal (`z.object({})` is valid but noisy); keep it.
    if entries.is_empty() {
        entries.push("  // no client-supplied fields".to_string());
    }
    entries
}

/// Render the input schemas (Create/Update) and the router for one model.
fn render_router(model: &Model, ast: &Ast) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl build --target trpc`. Do not edit by hand.\n");
    out.push_str("// Source of truth: the OSDL schema.\n");
    out.push_str("import { z } from \"zod\";\n");
    out.push_str("import { initTRPC } from \"@trpc/server\";\n");
    out.push('\n');

    // Create / Update input schemas.
    let create_body = zod_object_body(model, ast, false);
    let update_body = zod_object_body(model, ast, false);

    // The output schema reuses the full model shape (all fields).
    let mut full: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    full.sort_by(|a, b| a.name.cmp(&b.name));
    let mut out_entries = Vec::new();
    for f in &full {
        if !f.polymorphic_targets.is_empty() {
            let t = format!("{}_type", to_snake(&f.name));
            let i = format!("{}_id", to_snake(&f.name));
            out_entries.push(format!("  {t}: z.string(),"));
            out_entries.push(format!("  {i}: z.string(),"));
            continue;
        }
        out_entries.push(format!("  {}: {},", f.name, zod_field_schema(f)));
    }

    out.push_str(&format!(
        "export const {}CreateInput = z.object({{\n",
        model.name
    ));
    for e in &create_body {
        out.push_str(e);
        out.push('\n');
    }
    out.push_str("});\n\n");
    out.push_str(&format!(
        "export const {}UpdateInput = z.object({{\n",
        model.name
    ));
    for e in &update_body {
        out.push_str(e);
        out.push('\n');
    }
    out.push_str("});\n\n");
    out.push_str(&format!(
        "export const {}Output = z.object({{\n",
        model.name
    ));
    for e in &out_entries {
        out.push_str(e);
        out.push('\n');
    }
    out.push_str("});\n\n");

    // Router.
    out.push_str("const t = initTRPC.create();\n");
    out.push_str(&format!(
        "export const {}Router = t.router({{\n",
        model.name
    ));
    out.push_str(&format!(
        "  list: t.procedure.output(z.array({}Output)).query(({{ ctx }}) => {{\n",
        model.name
    ));
    out.push_str("    // TODO: return ctx.db.<model>.findMany();\n");
    out.push_str(
        &"    return [] as unknown as z.infer<typeof {}Output>[];\n"
            .replace("<model>", &model.name.to_lowercase()),
    );
    out.push_str("  }),\n");
    out.push_str(&format!(
        "  get: t.procedure.input(z.object({{ id: z.string() }})).output({}Output).query(({{ input }}) => {{\n",
        model.name
    ));
    out.push_str("    // TODO: return ctx.db.<model>.findUnique({ where: { id: input.id } });\n");
    out.push_str(
        &"    throw new Error(\"not implemented\");\n"
            .replace("<model>", &model.name.to_lowercase()),
    );
    out.push_str("  }),\n");
    out.push_str(&format!(
        "  create: t.procedure.input({}CreateInput).output({}Output).mutation(({{ input }}) => {{\n",
        model.name, model.name
    ));
    out.push_str("    // TODO: return ctx.db.<model>.create({ data: input });\n");
    out.push_str(
        &"    throw new Error(\"not implemented\")\n"
            .replace("<model>", &model.name.to_lowercase()),
    );
    out.push_str("  }),\n");
    out.push_str(&format!(
        "  update: t.procedure.input(z.object({{ id: z.string(), data: {}UpdateInput }})).output({}Output).mutation(({{ input }}) => {{\n",
        model.name, model.name
    ));
    out.push_str("    // TODO: return ctx.db.<model>.update({ where: { id: input.id }, data: input.data });\n");
    out.push_str(
        &"    throw new Error(\"not implemented\")\n"
            .replace("<model>", &model.name.to_lowercase()),
    );
    out.push_str("  }),\n");
    out.push_str(&format!(
        "  remove: t.procedure.input(z.object({{ id: z.string() }})).mutation(({{ input }}) => {{\n",
    ));
    out.push_str("    // TODO: return ctx.db.<model>.delete({ where: { id: input.id } });\n");
    out.push_str(&"    return { id: input.id };\n".replace("<model>", &model.name.to_lowercase()));
    out.push_str("  }),\n");
    out.push_str("});\n");
    out
}

fn render_barrel(routers: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl build --target trpc`. Do not edit by hand.\n");
    out.push_str("import { initTRPC } from \"@trpc/server\";\n\n");
    for r in routers {
        out.push_str(&format!("import {{ {r} }} from \"./{r}\";\n"));
    }
    out.push('\n');
    out.push_str("const t = initTRPC.create();\n\n");
    out.push_str("export const appRouter = t.mergeRouters(\n");
    for (i, r) in routers.iter().enumerate() {
        let comma = if i + 1 == routers.len() { "" } else { "," };
        out.push_str(&format!("  {r}{comma}\n"));
    }
    out.push_str(");\n");
    out
}

fn render_index(routers: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl build --target trpc`. Do not edit by hand.\n");
    out.push_str("export * from \"./routers\";\n");
    out.push_str("export type AppRouter = typeof appRouter;\n");
    let _ = routers;
    out
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    fn render(src: &str) -> String {
        let ast = parse(src).expect("parse");
        osdl_core::Validator::validate(&ast, Some(Target::Trpc)).expect("validate");
        let r = TrpcRenderer::new(Target::Trpc);
        let files = r.render(&ast).unwrap();
        let mut out = String::new();
        for (_, c) in files {
            out.push_str(&c);
        }
        out
    }

    #[test]
    fn emits_router_with_crud() {
        let src = "User
  id uuid -pk
  email string -uniq
  deletedAt datetime -softdelete -null
  age int -null
";
        let out = render(src);
        assert!(out.contains("import { z } from \"zod\";"));
        assert!(out.contains("import { initTRPC } from \"@trpc/server\";"));
        assert!(out.contains("export const UserRouter = t.router({"));
        // CRUD procedures present.
        assert!(out.contains("list: t.procedure.output(z.array(UserOutput))"));
        assert!(out.contains("get: t.procedure.input(z.object({ id: z.string() }))"));
        assert!(out.contains("create: t.procedure.input(UserCreateInput)"));
        assert!(out.contains(
            "update: t.procedure.input(z.object({ id: z.string(), data: UserUpdateInput }))"
        ));
        assert!(out.contains("remove: t.procedure.input(z.object({ id: z.string() }))"));
        // Managed fields (pk, soft-delete) excluded from the create input:
        // the create-input block must contain only age + email.
        assert!(out.contains(
            "export const UserCreateInput = z.object({\n  age: z.number().int().nullable(),\n  email: z.string() /* unique */,\n});"
        ));
        // Output shape keeps the managed column (nullable soft-delete marker).
        assert!(out.contains("deletedAt: z.string().datetime().nullable(),"));
    }

    #[test]
    fn output_schema_includes_all_fields() {
        let src = "User
  id uuid -pk
  email string -uniq
";
        let out = render(src);
        // Output schema is the full shape, pk included.
        assert!(out.contains("export const UserOutput = z.object({"));
        assert!(out.contains("id: z.string().uuid(),"));
    }

    #[test]
    fn merges_routers_in_barrel() {
        let src = "User
  id uuid -pk

Post
  id uuid -pk
";
        let out = render(src);
        assert!(out.contains("export const appRouter = t.mergeRouters("));
        assert!(out.contains("import { UserRouter } from \"./UserRouter\";"));
        assert!(out.contains("import { PostRouter } from \"./PostRouter\";"));
        assert!(out.contains("export type AppRouter = typeof appRouter;"));
    }
}
