//! Drizzle ORM schema interchange: bidirectional OSDL ↔ Drizzle (TypeScript).
//!
//! - [`drizzle_to_osdl`] (import, roadmap Phase 3.5): a Drizzle `pgTable` /
//!   `mysqlTable` / `sqliteTable` schema → an OSDL `Ast` (which the CLI then
//!   serializes via the shared `format_ast` formatter).
//! - [`render_drizzle`] (export): an OSDL `Ast` → a Drizzle TypeScript schema.
//!
//! The Drizzle import is intentionally conservative: it covers the common
//! declarative subset (tables, scalars, primary keys, not-null, unique,
//! defaults, foreign-key references, and native enums) and emits a valid
//! schema. Drizzle-specific features that have no OSDL analogue (e.g. composite
//! primary keys via `primaryKey()`, indexes via `index()`, `.$defaultFn()`)
//! are noted but not yet mapped.

#![allow(clippy::result_large_err)]

use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::{OsdlError, ParseError};
use osdl_core::formatter::format_ast;
use osdl_core::types::{FieldType, Intent, Reference, ScalarType};

/// Parse a Drizzle TypeScript schema into an OSDL `Ast`.
pub fn parse_drizzle(src: &str) -> Result<Ast, OsdlError> {
    let mut ast = Ast::new();
    let enums = parse_enums(src);

    // Walk the source line by line, capturing table blocks. A table is
    // `export const <name> = <dialect>Table('<sql_name>', { ... });`.
    let lines: Vec<&str> = src.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        if let Some((name, sql_name, body)) = scan_table(&lines, &mut i, line) {
            let model = build_model(&name, &sql_name, &body, &enums)?;
            ast.add_model(model);
        } else {
            i += 1;
        }
    }

    Ok(ast)
}

/// Convert a Drizzle TypeScript schema document into OSDL source.
pub fn drizzle_to_osdl(src: &str) -> Result<String, OsdlError> {
    let ast = parse_drizzle(src)?;
    Ok(format_ast(&ast))
}

/// Render an OSDL `Ast` as a Drizzle TypeScript schema (Postgres dialect).
pub fn render_drizzle(ast: &Ast) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl convert to-drizzle`. Do not edit by hand.\n");
    out.push_str("// Source of truth: the OSDL schema.\n\n");
    out.push_str("import { pgTable, serial, integer, bigint, text, varchar, boolean, timestamp, date, uuid, real, doublePrecision, json, jsonb, pgEnum } from 'drizzle-orm/pg-core';\n\n");

    for (_, model) in ast.models() {
        let sql_name = model.name.to_lowercase();
        out.push_str(&format!("export const {} = pgTable('{}', {{\n", model.name.to_lowercase(), sql_name));
        for (_, field) in model.fields() {
            out.push_str(&format!("  {}: {},\n", to_snake(&field.name), render_drizzle_column(field)));
        }
        out.push_str("});\n\n");
    }
    out
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

struct DrizzleEnum {
    name: String,
    values: Vec<String>,
}

fn parse_enums(src: &str) -> Vec<DrizzleEnum> {
    let mut enums = Vec::new();
    let lines: Vec<&str> = src.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();
        // export const roleEnum = pgEnum('role', ['admin', 'user']);
        if let Some(rest) = line.strip_prefix("export const ")
            && let Some(idx) = rest.find(" = pgEnum(")
        {
            let name = rest[..idx].trim().to_string();
            let args = &rest[idx + " = pgEnum(".len()..];
            if let Some(arr_start) = args.find('[') {
                let arr = &args[arr_start..];
                if let Some(arr_end) = arr.find(']') {
                    let inner = &arr[1..arr_end];
                    let values: Vec<String> = inner
                        .split(',')
                        .map(|s| s.trim().trim_matches('\'').trim_matches('"').to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                    enums.push(DrizzleEnum { name, values });
                }
            }
        }
        i += 1;
    }
    enums
}

// ---------------------------------------------------------------------------
// Table scanning
// ---------------------------------------------------------------------------

/// Scan from `lines[*start]`; if that line begins a table declaration, find
/// the matching closing `});` (tracking nested braces so `varchar('x', { ... })`
/// doesn't fool the scanner) and return `(model_name, sql_name, body)`.
fn scan_table(
    lines: &[&str],
    start: &mut usize,
    line: &str,
) -> Option<(String, String, String)> {
    let trimmed = line.trim();
    let rest = trimmed.strip_prefix("export const ")?;
    // <name> = <dialect>Table('<sql>', {
    let eq = rest.find(" = ")?;
    let name = rest[..eq].trim().to_string();
    let after_eq = &rest[eq + 3..];
    let open_paren = after_eq.find('(')?;
    // The dialect prefix before `Table(` (pg/mysql/sqlite).
    let inner = &after_eq[open_paren + 1..];
    // sql name is the first single-quoted string.
    let q1 = inner.find('\'')?;
    let q2 = inner[q1 + 1..].find('\'')?;
    let sql_name = inner[q1 + 1..q1 + 1 + q2].to_string();
    // Body opens at the first `{` on this same line.
    // Global char offset of `{` within the original `line`.
    let line_brace = line.find('{')?;

    let mut depth = 1i32; // we've entered the table body
    let mut body = String::new();
    // Start on the current line, just after the opening brace.
    accumulate(&mut depth, &mut body, &line[line_brace + 1..]);
    let mut j = *start + 1;
    while j < lines.len() {
        accumulate(&mut depth, &mut body, lines[j]);
        if depth == 0 {
            *start = j + 1;
            return Some((name, sql_name, body));
        }
        j += 1;
    }
    // No closing found; advance past the end.
    *start = lines.len();
    None
}

/// Append `line` text to `body` while tracking brace depth inside string
/// literals; stop once the opening brace is balanced (depth hits 0).
fn accumulate(depth: &mut i32, body: &mut String, line: &str) {
    let mut in_str = false;
    let mut esc = false;
    for c in line.chars() {
        if esc {
            esc = false;
            body.push(c);
            continue;
        }
        match c {
            '\\' => {
                esc = true;
                body.push(c);
            }
            '\'' | '"' => {
                in_str = !in_str;
                body.push(c);
            }
            '{' if !in_str => {
                *depth += 1;
                body.push(c);
            }
            '}' if !in_str => {
                *depth -= 1;
                body.push(c);
                if *depth == 0 {
                    return;
                }
            }
            _ => body.push(c),
        }
    }
    body.push('\n');
}

// ---------------------------------------------------------------------------
// Column building
// ---------------------------------------------------------------------------

fn build_model(
    name: &str,
    _sql_name: &str,
    body: &str,
    enums: &[DrizzleEnum],
) -> Result<Model, OsdlError> {
    let mut model = Model {
        name: name.to_string(),
        fields: la_arena::Arena::new(),
        field_index: vec![],
        line: 1,
        indexes: vec![],
        primary_key: vec![],
    };

    // Each field line: `<col>: <type>(...).mod1().mod2(),`
    for raw in body.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with("//") || line.starts_with('}') {
            continue;
        }
        // Strip trailing comma and any trailing comment.
        let line = match line.find("//") {
            Some(i) => &line[..i],
            None => line,
        };
        let line = line.trim_end_matches(',').trim();
        let Some(colon) = line.find(':') else { continue };
        let col = line[..colon].trim().to_string();
        let expr = line[colon + 1..].trim().to_string();
        if col.is_empty() || expr.is_empty() {
            continue;
        }
        // Skip composite PK/index helper lines.
        if col == "primaryKey" || col == "index" || col == "$inferSelect" || col == "$inferInsert" {
            continue;
        }
        let field = build_field(&col, &expr, enums)?;
        model.add_field(field);
    }

    Ok(model)
}

fn build_field(col: &str, expr: &str, enums: &[DrizzleEnum]) -> Result<Field, OsdlError> {
    // expr like `serial('id').primaryKey()` or
    // `varchar('email', { length: 255 }).notNull().unique()` or
    // `integer('author_id').notNull().references(() => users.id)`.
    let Some(paren) = expr.find('(') else {
        return Err(OsdlError::Parse(ParseError::new(format!(
            "cannot parse drizzle column `{col}: {expr}`"
        ))));
    };
    let type_name = expr[..paren].trim().to_string();
    let rest = &expr[paren..];
    let modifiers = collect_modifiers(rest);

    let mut field = Field {
        custom_type: None,
        name: col.to_string(),
        ty: FieldType::Scalar(ScalarType::String),
        intents: vec![],
        enum_variants: vec![],
        default_value: None,
        m2m_target: None,
        check_expr: None,
        polymorphic_targets: vec![],
        on_delete: None,
        on_update: None,
        numeric_precision: None,
        numeric_scale: None,
        through_model: None,
        line: 1,
    };

    // Base type mapping.
    field.ty = map_drizzle_type(&type_name, enums, &mut field);

    for m in &modifiers {
        match m.name.as_str() {
            "primaryKey" => field.intents.push(Intent::Pk),
            "notNull" => {} // OSDL uses -null for *nullable*; notNull means no -null.
            "unique" => field.intents.push(Intent::Uniq),
            "default" => {
                if let Some(v) = &m.args {
                    field.default_value = Some(strip_quotes(v));
                }
            }
            "references" => {
                if let Some(v) = &m.args {
                    // `() => users.id` or `() => users.id, fk => fk...`
                    if let Some(arrow) = v.find("=>") {
                        let rhs = v[arrow + 2..].trim();
                        let rhs = rhs.split(',').next().unwrap_or(rhs).trim();
                        let parts: Vec<&str> = rhs.split('.').collect();
                        if parts.len() == 2 {
                            field.ty = FieldType::Ref(Reference {
                                model: parts[0].to_string(),
                                field: parts[1].to_string(),
                            });
                            // A reference is not-null by default in OSDL.
                            field.intents.retain(|x| *x != Intent::Null);
                        }
                    }
                }
            }
            _ => {}
        }
    }

    // OSDL marks *nullable* fields with `-null`. Drizzle marks *non-null* with
    // `.notNull()`. So: if the field is not a PK and not a FK reference, it is
    // nullable in Drizzle unless `.notNull()` was present — and we did NOT add
    // `-null` for notNull. Add `-null` for everything that isn't pk/ref and
    // wasn't explicitly made non-null.
    let is_pk = field.intents.iter().any(|i| matches!(i, Intent::Pk));
    let is_ref = matches!(field.ty, FieldType::Ref(_));
    let explicit_not_null = modifiers.iter().any(|m| m.name == "notNull");
    if !is_pk && !is_ref && !explicit_not_null {
        field.intents.push(Intent::Null);
    }

    Ok(field)
}

/// Drizzle `.notNull()` means non-nullable. OSDL represents nullable with
/// `-null`, so a non-null field simply has no `-null` intent. We never push
/// `Intent::Null` for notNull; we only use it to *remove* nullability. To keep
/// the model faithful, nullable fields (those WITHOUT notNull) should get
/// `-null`. We handle that in build_model post-processing instead. Here we just
/// avoid pushing Null for notNull.
fn collect_modifiers(rest: &str) -> Vec<Modifier> {
    // rest looks like `(args).mod1(args).mod2().mod3(args),` — but we already
    // stripped the trailing comma at the caller. Find the first `)` then parse
    // `.name(args?)` chains until end of string.
    let mut mods = Vec::new();
    // Skip the type's own argument list: find the matching `)` for the first `(`.
    let mut depth = 0i32;
    let bytes: Vec<char> = rest.chars().collect();
    // first '(' is at index 0 (rest starts with '('). Find its matching ')'.
    let mut first_close = None;
    for (k, &c) in bytes.iter().enumerate() {
        match c {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    first_close = Some(k);
                    break;
                }
            }
            _ => {}
        }
    }
    let Some(first_close) = first_close else { return mods };
    let tail = &rest[first_close + 1..];
    // Parse `.name(optional args)` chains.
    let mut j = 0;
    let tail_chars: Vec<char> = tail.chars().collect();
    while j < tail_chars.len() {
        // Skip non-'.' and leading '.'.
        while j < tail_chars.len() && tail_chars[j] != '.' {
            j += 1;
        }
        if j >= tail_chars.len() {
            break;
        }
        j += 1; // consume '.'
        // Read name.
        let name_start = j;
        while j < tail_chars.len() && tail_chars[j].is_alphanumeric() {
            j += 1;
        }
        let name: String = tail_chars[name_start..j].iter().collect();
        if name.is_empty() {
            break;
        }
        // Optional args.
        let mut args = None;
        if j < tail_chars.len() && tail_chars[j] == '(' {
            let open = j;
            let mut d = 0i32;
            while j < tail_chars.len() {
                match tail_chars[j] {
                    '(' => d += 1,
                    ')' => {
                        d -= 1;
                        if d == 0 {
                            j += 1;
                            break;
                        }
                    }
                    _ => {}
                }
                j += 1;
            }
            args = Some(tail_chars[open + 1..j - 1].iter().collect::<String>());
        }
        mods.push(Modifier { name, args });
    }
    mods
}

struct Modifier {
    name: String,
    args: Option<String>,
}

fn map_drizzle_type(type_name: &str, enums: &[DrizzleEnum], field: &mut Field) -> FieldType {
    // Enum?
    if let Some(e) = enums.iter().find(|e| e.name == type_name) {
        field.enum_variants = e.values.clone();
        return FieldType::Scalar(ScalarType::String);
    }
    match type_name {
        "serial" | "bigserial" => FieldType::Scalar(ScalarType::Int),
        "integer" | "int" | "smallint" => FieldType::Scalar(ScalarType::Int),
        "bigint" => FieldType::Scalar(ScalarType::BigInt),
        "text" | "varchar" | "char" | "citext" => FieldType::Scalar(ScalarType::String),
        "boolean" | "bool" => FieldType::Scalar(ScalarType::Bool),
        "timestamp" | "timestamptz" | "date" | "time" => FieldType::Scalar(ScalarType::DateTime),
        "uuid" => FieldType::Scalar(ScalarType::Uuid),
        "real" | "float" | "float4" | "float8" | "doublePrecision" | "numeric" | "decimal" | "decimaljs" => {
            FieldType::Scalar(ScalarType::Float)
        }
        "json" | "jsonb" => FieldType::Scalar(ScalarType::Json),
        "binary" | "bytea" => FieldType::Scalar(ScalarType::Binary),
        other => {
            // Unknown type — default to string.
            let _ = other;
            FieldType::Scalar(ScalarType::String)
        }
    }
}

fn strip_quotes(s: &str) -> String {
    s.trim().trim_matches('\'').trim_matches('"').to_string()
}

fn to_snake(s: &str) -> String {
    let mut out = String::new();
    let mut prev_lower = false;
    for c in s.chars() {
        if c.is_uppercase() {
            if prev_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_lower = false;
        } else {
            out.push(c);
            prev_lower = c.is_lowercase() || c.is_ascii_digit();
        }
    }
    out
}

fn render_drizzle_column(field: &Field) -> String {
    let (mut base, args) = drizzle_type_for(field);
    // A surrogate primary key of integer type is rendered as `serial`
    // (Postgres auto-increment); a plain integer column is `integer`.
    let is_pk = field.intents.iter().any(|i| matches!(i, Intent::Pk));
    if is_pk && base == "integer" {
        base = "serial";
    }
    let mut s = format!("{base}('{}'", to_snake(&field.name));
    if let Some(a) = args {
        s.push_str(&format!(", {a}"));
    }
    s.push(')');
    for intent in &field.intents {
        match intent {
            Intent::Pk => {
                s.push_str(".primaryKey()");
            }
            Intent::Uniq => s.push_str(".unique()"),
            Intent::Null => {} // nullable => nothing (Drizzle default)
            _ => {}
        }
    }
    if let Some(def) = &field.default_value {
        s.push_str(&format!(".default({})", default_for(def)));
    }
    if let FieldType::Ref(r) = &field.ty {
        s.push_str(&format!(
            ".notNull().references(() => {}.{})",
            r.model.to_lowercase(),
            to_snake(&r.field)
        ));
    }
    s
}

fn drizzle_type_for(field: &Field) -> (&'static str, Option<String>) {
    match &field.ty {
        FieldType::Scalar(st) => match st {
            ScalarType::Int => ("integer", None),
            ScalarType::BigInt => ("bigint", None),
            ScalarType::String => ("text", None),
            ScalarType::Bool => ("boolean", None),
            ScalarType::DateTime => ("timestamp", None),
            ScalarType::Uuid => ("uuid", None),
            ScalarType::Float => ("real", None),
            ScalarType::Json => ("jsonb", None),
            ScalarType::Binary => ("bytea", None),
            ScalarType::Date => ("date", None),
            ScalarType::Decimal => ("numeric", None),
        },
        FieldType::Ref(_) => ("integer", None),
        _ => ("text", None),
    }
}

fn default_for(def: &str) -> String {
    // OSDL defaults: now, 0, "", uuid(), autoincrement(). Map to Drizzle.
    match def {
        "now" => "now()".to_string(),
        "uuid()" => "uuid()".to_string(),
        "autoincrement()" => "autoIncrement()".to_string(),
        other => {
            let is_numeric = other.parse::<i64>().is_ok() || other.parse::<f64>().is_ok();
            let is_quoted = other.starts_with('"') || other.starts_with('\'');
            if is_numeric || is_quoted {
                other.to_string()
            } else {
                format!("'{other}'")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    const SAMPLE: &str = r#"
import { pgTable, serial, text, varchar, integer, timestamp, boolean, uuid, pgEnum } from 'drizzle-orm/pg-core';

export const roleEnum = pgEnum('role', ['admin', 'user']);

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  name: text('name'),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const posts = pgTable('posts', {
  id: serial('id').primaryKey(),
  authorId: integer('author_id').notNull().references(() => users.id),
  title: text('title').notNull(),
});
"#;

    #[test]
    fn import_parses_models() {
        let ast = parse_drizzle(SAMPLE).expect("parse drizzle");
        assert!(ast.model_by_name("users").is_some());
        assert!(ast.model_by_name("posts").is_some());
    }

    #[test]
    fn import_maps_scalar_types() {
        let ast = parse_drizzle(SAMPLE).expect("parse drizzle");
        let (_, u) = ast.models().find(|(_, m)| m.name == "users").unwrap();
        let id = u.field_by_name("id").unwrap();
        assert!(matches!(u.fields[id].ty, FieldType::Scalar(ScalarType::Int)));
        assert!(u.fields[id].has(Intent::Pk));
        let email = u.field_by_name("email").unwrap();
        assert!(u.fields[email].has(Intent::Uniq));
        assert!(!u.fields[email].has(Intent::Null));
        let name = u.field_by_name("name").unwrap();
        // name is nullable (no notNull) => OSDL -null.
        assert!(u.fields[name].has(Intent::Null));
    }

    #[test]
    fn import_resolves_reference() {
        let ast = parse_drizzle(SAMPLE).expect("parse drizzle");
        let (_, p) = ast.models().find(|(_, m)| m.name == "posts").unwrap();
        let author = p.field_by_name("authorId").unwrap();
        match &p.fields[author].ty {
            FieldType::Ref(r) => {
                assert_eq!(r.model, "users");
                assert_eq!(r.field, "id");
            }
            other => panic!("expected ref, got {other:?}"),
        }
    }

    #[test]
    fn round_trip_osdl_to_drizzle() {
        let osdl = "User\n  id uuid -pk\n  email string -uniq\n  name string\n  age int -null\n";
        let ast = parse(osdl).expect("parse osdl");
        let ts = render_drizzle(&ast);
        assert!(ts.contains("pgTable('user'"));
        assert!(ts.contains("id: uuid('id').primaryKey()"));
        assert!(ts.contains("email: text('email').unique()"));
        // age is nullable => no notNull in Drizzle.
        assert!(ts.contains("age: integer('age')"));
    }
}
