[package]
name = "osdl-codegen-ts-validators"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
osdl-core = { workspace = true }
osdl-parser = { workspace = true }

[dev-dependencies]
osdl-core = { workspace = true }
osdl-parser = { workspace = true }
