//! TypeScript renderer.
//!
//! Generates one `.ts` interface per OSDL model plus an `index.ts` barrel,
//! making OSDL the single source of truth for the frontend type layer. Output
//! is produced by string assembly over the typed [`Ast`] (no `syn` needed for
//! TS), deterministic and model-sorted, so it round-trips cleanly.

#![allow(clippy::result_large_err)]

use osdl_core::Target;
use osdl_core::ast::{Ast, Field, Model};
use osdl_core::errors::OsdlError;
use osdl_core::types::{FieldType, Intent, ScalarType};
use osdl_core::validator::CodeRenderer;

/// The TypeScript renderer.
pub struct TypeScriptRenderer {
    target: Target,
}

impl TypeScriptRenderer {
    pub fn new(target: Target) -> Self {
        Self { target }
    }
}

impl CodeRenderer for TypeScriptRenderer {
    fn target(&self) -> Target {
        self.target
    }

    fn render(&self, ast: &Ast) -> Result<Vec<(String, String)>, OsdlError> {
        let mut files = Vec::new();
        let mut names: Vec<String> = ast.models().map(|(_, m)| m.name.clone()).collect();
        names.sort();
        for name in &names {
            let (_, model) = ast
                .models()
                .find(|(_, m)| &m.name == name)
                .expect("model exists");
            files.push((format!("{name}.ts"), render_interface(model)));
        }
        files.push(("runtime.ts".to_string(), render_runtime(ast, &names)));
        Ok(files)
    }
}

/// Map a scalar to its TypeScript type.
fn ts_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::String => "string",
        ScalarType::Int => "number",
        ScalarType::BigInt => "number",
        ScalarType::Float => "number",
        ScalarType::Bool => "boolean",
        ScalarType::DateTime => "string", // ISO-8601 timestamp
        ScalarType::Date => "string",     // ISO date
        ScalarType::Uuid => "string",
        ScalarType::Json => "unknown",
        ScalarType::Binary => "Uint8Array",
    }
}

/// Map a field to its TypeScript type expression.
fn ts_type(field: &Field) -> String {
    let base = match &field.ty {
        FieldType::Scalar(s) => ts_scalar(*s).to_string(),
        FieldType::Ref(r) => format!("string // FK -> {}", r.model),
        FieldType::InferredRef(s) => s.clone(),
    };
    let optional = field.has(Intent::Null);
    format!("{base}{}", if optional { " | null" } else { "" })
}

fn render_interface(model: &Model) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines
        .push("// Generated by `osdl build --target typescript`. Do not edit by hand.".to_string());
    lines.push("// Source of truth: the OSDL schema.".to_string());
    lines.push(String::new());

    // Polymorphic references expand into a type/id pair; emit them first.
    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));

    let mut body: Vec<String> = Vec::new();
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            body.push(format!(
                "  /** polymorphic ref -> {} */",
                f.polymorphic_targets.join(", ")
            ));
            body.push(format!("  {}: string;", to_snake(&f.name) + "_type"));
            body.push(format!("  {}: string;", to_snake(&f.name) + "_id"));
            continue;
        }
        let mut comments = Vec::new();
        if f.has(Intent::Pk) {
            comments.push("primary key".to_string());
        }
        if f.has(Intent::Uniq) {
            comments.push("unique".to_string());
        }
        if f.has(Intent::Virtual) {
            comments.push("virtual (computed/serialized-only)".to_string());
        }
        if f.has(Intent::SoftDelete) {
            comments.push("soft-delete marker".to_string());
        }
        if let Some(expr) = &f.check_expr {
            comments.push(format!("check: {expr}"));
        }
        if let Some(def) = &f.default_value {
            comments.push(format!("default: {def}"));
        }
        if !comments.is_empty() {
            body.push(format!("  /** {} */", comments.join("; ")));
        }
        body.push(format!("  {}: {};", f.name, ts_type(f)));
    }

    lines.push(format!("export interface {} {{", model.name));
    for b in body {
        lines.push(b);
    }
    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// Emit a runtime layer: plain (no external deps) validators + serializers per
/// model. Interfaces are type-only; this makes the schema enforceable and
/// (de)serializable at runtime (e.g. validating API payloads on the client).
///
/// Each model gets a `validate<Model>(raw): <Model>` that throws on bad input,
/// and `serialize<Model>(m): unknown` for the wire shape.
fn render_runtime(ast: &Ast, names: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `osdl build --target typescript`. Do not edit by hand.\n");
    out.push_str("// Runtime validators + (de)serializers for the OSDL schema.\n");
    out.push_str("// No external dependencies — usable in any TS/JS runtime.\n\n");

    out.push_str("export type OSDLValidationError = { field: string; message: string };\n");
    out.push_str("export class OSDLValidationError extends Error {\n");
    out.push_str("  errors: OSDLValidationError[];\n");
    out.push_str("  constructor(errors: OSDLValidationError[]) {\n");
    out.push_str("    super(\"validation failed: \" + errors.map((e) => `${e.field}: ${e.message}`).join(\"; \"));\n");
    out.push_str("    this.errors = errors;\n");
    out.push_str("  }\n}\n\n");

    for name in names {
        let (_, model) = ast
            .models()
            .find(|(_, m)| &m.name == name)
            .expect("model exists");
        out.push_str(&render_model_runtime(model));
        out.push('\n');
    }
    out.push('\n');
    out
}

/// Runtime guard for a single field: returns the JS check expression (boolean)
/// given the accessor `v` and the field metadata.
fn ts_runtime_guard(field: &Field) -> (String, Vec<String>) {
    // (check_expr, error_messages)
    match &field.ty {
        FieldType::Scalar(s) => {
            let (check, msg) = match s {
                ScalarType::String | ScalarType::Json | ScalarType::Binary => (
                    "typeof v === \"string\" || v instanceof Uint8Array".to_string(),
                    "expected string".to_string(),
                ),
                ScalarType::Int | ScalarType::BigInt | ScalarType::Float => (
                    "typeof v === \"number\" && !Number.isNaN(v)".to_string(),
                    "expected number".to_string(),
                ),
                ScalarType::Bool => (
                    "typeof v === \"boolean\"".to_string(),
                    "expected boolean".to_string(),
                ),
                ScalarType::DateTime | ScalarType::Date | ScalarType::Uuid => (
                    "typeof v === \"string\"".to_string(),
                    "expected string".to_string(),
                ),
            };
            (check, vec![msg])
        }
        FieldType::Ref(_) | FieldType::InferredRef(_) => (
            "typeof v === \"string\"".to_string(),
            vec!["expected reference id (string)".to_string()],
        ),
    }
}

fn render_model_runtime(model: &Model) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!(
        "export function validate{}<T extends unknown>(raw: T): {} {{",
        model.name, model.name
    ));
    lines.push("  const errors: OSDLValidationError[] = [];".to_string());
    lines.push("  const v = raw as any;".to_string());

    let mut fields: Vec<&Field> = model.fields().map(|(_, f)| f).collect();
    fields.sort_by(|a, b| a.name.cmp(&b.name));
    for f in &fields {
        if !f.polymorphic_targets.is_empty() {
            let t = format!("{}_type", to_snake(&f.name));
            let i = format!("{}_id", to_snake(&f.name));
            lines.push(format!("  if (typeof v[\"{t}\"] !== \"string\") errors.push({{ field: \"{t}\", message: \"expected string\" }});"));
            lines.push(format!("  if (typeof v[\"{i}\"] !== \"string\") errors.push({{ field: \"{i}\", message: \"expected string\" }});"));
            continue;
        }
        let (guard, msgs) = ts_runtime_guard(f);
        let optional = f.has(Intent::Null);
        let presence = if optional {
            format!(
                "(v[\"{name}\"] === undefined || v[\"{name}\"] === null || ({guard}))",
                name = f.name,
                guard = guard
            )
        } else {
            format!(
                "(v[\"{name}\"] !== undefined && v[\"{name}\"] !== null && ({guard}))",
                name = f.name,
                guard = guard
            )
        };
        let msg = if msgs.is_empty() {
            "invalid value".to_string()
        } else {
            msgs[0].clone()
        };
        if optional {
            lines.push(format!(
                "  if (v[\"{name}\"] !== undefined && v[\"{name}\"] !== null && !({guard})) errors.push({{ field: \"{name}\", message: \"{msg}\" }});",
                name = f.name, guard = guard, msg = msg
            ));
        } else {
            lines.push(format!(
                "  if (v[\"{name}\"] === undefined || v[\"{name}\"] === null || !({guard})) errors.push({{ field: \"{name}\", message: \"{msg}\" }});",
                name = f.name, guard = guard, msg = msg
            ));
        }
        let _ = presence;
    }
    lines.push("  if (errors.length > 0) throw new OSDLValidationError(errors);".to_string());
    lines.push("  return v as {};".to_string());
    lines.push("}".to_string());

    // Serializer: passes the object through (wire shape === TS shape for OSDL).
    lines.push(format!(
        "export function serialize{}(m: {}): unknown {{",
        model.name, model.name
    ));
    lines.push("  return m;".to_string());
    lines.push("}".to_string());
    lines.join("\n")
}

fn render_barrel(names: &[String]) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines
        .push("// Generated by `osdl build --target typescript`. Do not edit by hand.".to_string());
    lines.push(String::new());
    for n in names {
        lines.push(format!("export type {{ {n} }} from \"./{n}\";"));
    }
    lines.push(String::new());
    lines.join("\n")
}

/// `ModelName` -> `model_name` (snake_case).
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if i != 0 && c.is_uppercase() {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use osdl_parser::parse;

    fn render(src: &str) -> String {
        let ast = parse(src).unwrap();
        osdl_core::Validator::validate(&ast, Some(Target::TypeScript)).unwrap();
        let r = TypeScriptRenderer::new(Target::TypeScript);
        let files = r.render(&ast).unwrap();
        let mut out = String::new();
        for (_, c) in files {
            out.push_str(&c);
        }
        out
    }

    #[test]
    fn emits_interface_with_types() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null -check \"age >= 0\"\n  bio string -virtual\n";
        let out = render(src);
        assert!(out.contains("export interface User"));
        assert!(out.contains("id: string;") || out.contains("id: string //"));
        assert!(out.contains("email: string;"));
        assert!(out.contains("age: number | null;"));
        assert!(out.contains("virtual (computed/serialized-only)"));
        assert!(out.contains("check: age >= 0"));
    }

    #[test]
    fn polymorphic_expands_to_pair() {
        let src = "Comment\n  id uuid -pk\n  target -polymorphic Post,Video\n";
        let out = render(src);
        assert!(out.contains("target_type: string;"));
        assert!(out.contains("target_id: string;"));
    }

    #[test]
    fn deterministic_barrel_order() {
        let src = "Zebra\n  id uuid -pk\nApple\n  id uuid -pk\n";
        let out = render(src);
        let zebra = out.find("Zebra").unwrap();
        let apple = out.find("Apple").unwrap();
        assert!(apple < zebra, "barrel must be sorted: {out}");
    }

    #[test]
    fn emits_runtime_validator() {
        let src = "User\n  id uuid -pk\n  email string -uniq\n  age int -null\n";
        let out = render(src);
        // Runtime validators + (de)serializers are emitted alongside the types.
        assert!(out.contains("export function validateUser<"));
        assert!(out.contains("export function serializeUser("));
        assert!(out.contains("OSDLValidationError"));
        // Non-null field is required; nullable field is optional.
        assert!(out.contains("errors.push({ field: \"id\""));
        assert!(out.contains("if (v[\"age\"] !== undefined"));
    }
}
