[package]
name = "odsl-codegen-trpc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
odsl-core = { workspace = true }
odsl-parser = { workspace = true }
odsl-codegen-ts-validators = { workspace = true }

[dev-dependencies]
odsl-core = { workspace = true }
odsl-parser = { workspace = true }
