[package]
name = "odsl-codegen-seaorm"
description = "SeaORM 2.x renderer for ODSL"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
odsl-core.workspace = true
odsl-codegen.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
prettyplease.workspace = true

[dev-dependencies]
odsl-parser.workspace = true
insta.workspace = true
